# Generated by Django 4.2.3 on 2023-07-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='user',
        ),
    ]
